blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/website/urls.py
from django.urls import path
from . import views


urlpatterns = [path('', views.PostView.as_view()),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('comments/<int:pk>/', views.AddComment.as_view(), name='AddComments'),
               path('<int:pk>/add_like/', views.Addlikes.as_view(), name='AddLikes'),
               path('<int:pk>/del_like/', views.Dislike.as_view(), name='Dellikes')]

blog/website/models.py
from django.db import models

class Post(models.Model):
    '''Данные о записи'''
    title = models.CharField('Заголовок записи', max_length=100)
    descriptions = models.TextField('Описание', max_length=1500)
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    image = models.ImageField('Картинка', upload_to='image/')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    '''Создание комментариев'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comment = models.TextField('Текст комментария', max_length=200)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.email}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

class Likes(models.Model):
    '''лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публекация', on_delete=models.CASCADE)

blog/website/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.views.generic.base import View
from .models import Post, Likes
from .form import CommentsForm


class PostView(View):
    '''Вывод записи'''
    def get(self, request):
        posts = Post.objects.all().order_by('-date')
        return render(request, 'website/blog.html', {'post_list': posts})

class PostDetail(View):
    """Отдельная страница записи"""
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'website/blog_detail.html', {'post': post})

class AddComment(View):
    """Добавление комментариев"""
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')

def get_client_ip(request):
    x_forward = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forward:
        ip = x_forward.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

class Addlikes(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')

class Dislike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            like = Likes.objects.get(ip=ip_client)
            like.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

blog/templates/website/blog.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Авто-блог</title>
    <link rel="shortcut icon" type="image/png" href="..\images\image\favicon.ico"/>
<meta name="keywords" content="free css templates, blog design, 2-column, web design, CSS, HTML" />
<meta name="description" content="Design Blog - free css template, 2-column blog layout" />
<link href="{% static 'css/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
<script language="javascript" type="text/javascript">
function clearText(field)
{
    if (field.defaultValue == field.value) field.value = '';
    else if (field.value == '') field.value = field.defaultValue;
}
</script>
</head>
<body>

<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">

    <div id="templatemo_header">

        <div id="site_title">
            <a href="/" target="_parent"><span>Blog</span>

                <span class="tagline">Авто-блог</span>
            </a>
        </div> <!-- end of site_title -->


        <div class="cleaner"></div>

    </div> <!-- end of header -->

    <div id="templatemo_menu">
        <ul>
            <li><a href="/" class="current"><span></span>Главная</a></li>
            <li><a href="/admin"><span></span>Админ</a></li>
            <li><a href="https://www.linkedin.com/in/igor-pravdin-763qa/"><span></span>LinkedIn</a></li>
        </ul>

    </div> <!-- end of templatemo_menu -->


        <div id="templatemo_content">
            {% for i in post_list %}
        	<div class="post_box">

                <h2><a href="{{ i.id }}">{{ i.title }}</a></h2>
                <div class="news_meta">{{ i.date }}
                <div class="image_wrapper"><img src="{{ i.image.url}}" width=100% alt="image 1" /></div>
              <p align="justify">{{ i.descriptions|truncatechars:500 }}<a href="{{ i.id }}" class="continue"> Читать далее ...</a></p>
              <div class="cleaner"></div>
            </div>
            {% endfor %}
          </div>

        </div>

        <div id="templatemo_sidebar">

        </div>

    	<div class="cleaner"></div>


</div>
<div class="cleaner"></div>
</div>




</body>
</html>

blog/templates/website/blog_detail.html
{% load static %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Авто-блог</title>
    <link rel="shortcut icon" type="image/png" href="..\images\image\favicon.ico"/>
<meta name="keywords" content="free css templates, blog design, 2-column, web design, CSS, HTML" />
<meta name="description" content="Design Blog - free css template, 2-column blog layout" />
<link href="{% static 'css/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
<script language="javascript" type="text/javascript">
function clearText(field)
{
    if (field.defaultValue == field.value) field.value = '';
    else if (field.value == '') field.value = field.defaultValue;
}
</script>
</head>
<body>

<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">

    <div id="templatemo_header">

        <div id="site_title">
            <a href="/" target="_parent"><span>Blog</span>

                <span class="tagline">Авто-блог</span>
            </a>
        </div> <!-- end of site_title -->


        <div class="cleaner"></div>

    </div> <!-- end of header -->

    <div id="templatemo_menu">
        <ul>
            <li><a href="/" class="current"><span></span>Главная</a></li>
            <li><a href="/admin"><span></span>Админ</a></li>
            <li><a href="https://www.linkedin.com/in/igor-pravdin-763qa/"><span></span>LinkedIn</a></li>
        </ul>


    </div> <!-- end of templatemo_menu -->


        <div id="templatemo_content">
        	<div class="post_box">
                <h2><a href="#">{{ post.title }}</a></h2>
                <div class="news_meta">{{ post.date }}
                <div class="image_wrapper"><img src="{{ post.image.url}}" width=100% alt="image 1" /></div>
              <p align="justify">{{ post.descriptions }}</p>
                    <p align="right">Автор: {{ post.author }}</p>
                    <div class="like">
                        <br>
                        <p style="font-size: 15px; color: #00FF00; border:2px solid #00FF00; border-radius:3px; width: 120px; text-align:justify;  margin:5px; padding:5px;" >Понравилось: {{ post.likes_set.all.count }}</p>
                        <br>
                        <a href="{% url 'AddLikes' post.id %}"><img src="..\images\image\like.png" width="25"
   height="25" alt="Нравится"></a>
                        <a href="{% url 'AddLikes' post.id %}">Нравится   </a>
                        <a href="{% url 'Dellikes' post.id %}"><img src="..\images\image\dis.png" width="25"
   height="25" alt="Не нравится"></a>
                        <a href="{% url 'Dellikes' post.id %}">Не нравится</a>
                    </div>
              <div class="cleaner"></div>
            </div>
          </div>

        </div>

        <div id="templatemo_sidebar">
        <div class="form-comment">
            <br>
            <br>
            <br>
            <h3>Оставить комментарий</h3>
            <div>
                <form action="{% url 'AddComments' post.id %}" method="post">
                    {% csrf_token %}
                <div>
                    <label>Ваш комментарий</label>
                    <textarea name="text_comment"></textarea>
                    </div>
                    <div>
                        <label>Ваше имя*</label>
                    <input type="text" name="name">
                        </div>
                     <div>
                         <label>Ваш Email*</label>
                    <input type="email" name="email">
                         </div>
                     <div>
                         <input type="submit">
                         </div>
                    </form>
            </div>
        </div>
            <div>
            {% for co in post.comments_set.all %}
            <div class="view-comment">
                <br>
                <p style="margin-left: 10px"><b>{{ co.name }}</b></p>
                <p style="color: #FFF8DC; border:2px solid #00CED1; border-radius:5px; width: 280px; text-align:justify;  margin:5px; padding:12px;" >{{co.text_comment }}</p>
                </div>
            {% endfor %}
        </div>
        </div>

    	<div class="cleaner"></div>
    </div>


<div class="cleaner"></div>
</div>




</body>
</html>